### ISSUE TITLE
Nominatim EULA requires `User-Agent`or `Referer` headers

### ISSUE THREAD

**Issue by russweas** [grantshandy/nominatim-rs#1]
Really cool project! I'm planning on using it for a tropical seroprevalence research project I'm involved in. One thing I noticed though is that surf isn't including these headers with its requests, which could get an IP blocked by OSM. 

I can push a PR later today to address this, but I'm not sure how you would like to handle passing in the application name to the service. I was thinking about just creating a `NominatimConfig` struct that is passed in as the first parameter for every request. 

Per [Nominatim usage policy](https://operations.osmfoundation.org/policies/nominatim/):
> Provide a valid HTTP Referer or User-Agent identifying the application (stock User-Agents as set by http libraries will not do).

**Comment by grantshandy** [comment]
Thanks! I didn't catch this at all.

I'd be happy to merge any pull request you create, this looks important. I hope nominatim-rs helps you in any future projects.

\- Grant

**Comment by grantshandy** [comment]
Thanks @russweas for your amazing work, I published it to crates.io at https://crates.io/crates/nominatim.
